# ---
# Alveo U50 Master Constraint File (XDC)
# Device: Xilinx UltraScale+ XCU50-2FSVH2104E
# Board:  Xilinx Alveo U50 Data Center Accelerator Card
# Vendor: AMD-Xilinx
# Doc:    https://docs.amd.com/r/en-US/ug1371-u50-reconfig-accel
# Schematic: Under NDA — pin data from Xilinx board files package
#
# USE CASE: PCIe-attached FPGA for data center workloads, ML inference,
# network processing, HPC acceleration. Not a development board — typically
# installed in a server PCIe slot.
#
# CRITICAL NOTES:
#   1. The U50 has NO on-board DRAM in the traditional sense. It has 8 GB HBM2
#      (High Bandwidth Memory) directly on the package — accessed via HBM IP.
#   2. The primary user clock comes from the PCIe reference clock or the
#      on-board 100 MHz SI5335 oscillator — NOT a simple crystal.
#   3. Most U50 designs use Vitis/XRT shell (xilinx_u50_gen3x16_xdma_base_4)
#      which provides AXI4 interfaces, PCIe, and HBM management.
#   4. If using the Vitis shell, you do NOT constrain the clocks yourself —
#      the shell platform provides them as port interfaces.
#
# THIS FILE: Covers the bare-metal (non-shell) constraint approach.
# For Vitis shell designs, see the platform XDC included with the shell.
# ---


# ---
# SYSTEM CLOCKS
# ---

## 100 MHz System Clock (SI5335A oscillator — bank 67)
## This is the free-running reference clock available in all operating modes.
set_property PACKAGE_PIN BJ44  [get_ports sys_clk_p]
set_property PACKAGE_PIN BJ43  [get_ports sys_clk_n]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_p]
set_property IOSTANDARD DIFF_SSTL12 [get_ports sys_clk_n]
create_clock -period 10.000 -name sys_clk [get_ports sys_clk_p]

## PCIe Reference Clock (100 MHz from PCIe slot — used by PCIe core)
## Connected to dedicated MGTREFCLK input — handled by PCIe IP automatically
## set_property PACKAGE_PIN AM10 [get_ports pcie_refclk_p]   ;# MGTREFCLK — do not constrain here
## PCIe IP generates its own clock constraints


# ---
# RESETS & STATUS
# ---

## System Reset (active low — from PCIe or external)
set_property PACKAGE_PIN BG45  [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS12 [get_ports sys_rst_n]
set_false_path -from [get_ports sys_rst_n]


# ---
# PCIe INTERFACE  —  Gen3 x16
# ---
#
# The U50 connects to the host via PCIe Gen3 x16 (or Gen4 x8 depending on slot).
# PCIe is implemented using the Xilinx PCIe IP (pcie4_uscale_plus or xdma).
# The PCIe IP handles all differential lane constraints internally.
# Do NOT manually constrain individual TX/RX lanes.
#
# When using Xilinx PCIe IP:
#   1. Set the PCIe location constraint in the IP configuration
#   2. The IP XDC (generated by the IP) covers all lane assignments
#   3. Your only job is to constrain the reference clock (above)
#
# PCIe lane location (for reference — used by IP, not manually):
#   TX lanes: MGTHTXP0[0:15] / MGTHTXN0[0:15]
#   RX lanes: MGTHRXP0[0:15] / MGTHRXN0[0:15]
#   These are on the dedicated GTH transceivers in banks 227–232


# ---
# HBM2 (High Bandwidth Memory — 8 GB on-package)
# ---
#
# The U50 has 8 GB HBM2 organized as 2 stacks × 16 pseudo-channels.
# HBM is accessed through Xilinx HBM IP (hbm_0).
# The HBM IP handles all memory interface constraints.
#
# Bandwidth: Up to 460 GB/s aggregate (theoretical)
# Latency: ~120 ns
#
# To use HBM in your design:
#   1. Add HBM IP in Vivado IP Catalog
#   2. Configure number of AXI ports (up to 32 ports, AXI4 protocol)
#   3. Connect your logic to AXI4 master ports
#   4. The HBM IP XDC handles all internal timing
#
# The HBM reference clock (APB clock at 100 MHz) is supplied from sys_clk above.


# ---
# QSFP28 PORTS  —  2× QSFP28 (100G Ethernet / optical)
# ---
#
# The U50 has 2 QSFP28 cages for 100GbE or custom protocols.
# Each QSFP28 connects to 4 GTY transceivers.
#
# QSFP0 — banks 128–131
# QSFP1 — banks 132–135
#
# For 100GbE: Use Xilinx 100G MAC IP (cmac_usplus)
# The CMAC IP handles all GTY transceiver constraints.
#
## QSFP0 Control (I2C management + module present detect)
set_property PACKAGE_PIN BE17  [get_ports qsfp0_modprsl]     ;# Module present (active low)
set_property PACKAGE_PIN BE16  [get_ports qsfp0_resetl]      ;# Module reset (active low)
set_property PACKAGE_PIN BD18  [get_ports qsfp0_lpmode]      ;# Low power mode
set_property PACKAGE_PIN BE18  [get_ports qsfp0_intl]        ;# Interrupt (active low)
set_property PACKAGE_PIN BC18  [get_ports qsfp0_modsell]     ;# Module select (active low)

## QSFP1 Control
set_property PACKAGE_PIN AY20  [get_ports qsfp1_modprsl]
set_property PACKAGE_PIN AY19  [get_ports qsfp1_resetl]
set_property PACKAGE_PIN BA20  [get_ports qsfp1_lpmode]
set_property PACKAGE_PIN AY17  [get_ports qsfp1_intl]
set_property PACKAGE_PIN AW17  [get_ports qsfp1_modsell]

set_property IOSTANDARD LVCMOS12 [get_ports qsfp0_modprsl]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp0_resetl]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp0_lpmode]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp0_intl]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp0_modsell]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp1_modprsl]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp1_resetl]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp1_lpmode]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp1_intl]
set_property IOSTANDARD LVCMOS12 [get_ports qsfp1_modsell]

set_false_path -from [get_ports qsfp0_modprsl]
set_false_path -from [get_ports qsfp0_intl]
set_false_path -from [get_ports qsfp1_modprsl]
set_false_path -from [get_ports qsfp1_intl]
set_false_path -to   [get_ports qsfp0_resetl]
set_false_path -to   [get_ports qsfp0_lpmode]
set_false_path -to   [get_ports qsfp0_modsell]
set_false_path -to   [get_ports qsfp1_resetl]
set_false_path -to   [get_ports qsfp1_lpmode]
set_false_path -to   [get_ports qsfp1_modsell]


# ---
# I2C (Card management — for reading temperature, power, serial number)
# ---

set_property PACKAGE_PIN BR37  [get_ports i2c_scl]
set_property PACKAGE_PIN BN37  [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_scl]
set_property IOSTANDARD LVCMOS18 [get_ports i2c_sda]
set_false_path -from [get_ports i2c_scl]
set_false_path -from [get_ports i2c_sda]
set_false_path -to   [get_ports i2c_scl]
set_false_path -to   [get_ports i2c_sda]


# ---
# UART (for board management — access via PCIe or dedicated connector)
# ---

set_property PACKAGE_PIN BU28  [get_ports uart_txd]
set_property PACKAGE_PIN BT28  [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS18 [get_ports uart_rxd]
set_false_path -from [get_ports uart_rxd]
set_false_path -to   [get_ports uart_txd]


# ---
# CONFIGURATION BANK SETTINGS
# ---

set_property CFGBVS GND         [current_design]
set_property CONFIG_VOLTAGE 1.8 [current_design]
set_property BITSTREAM.CONFIG.EXTMASTERCCLK_EN DIV-1 [current_design]
set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
