# ---
# MIPI CSI-2 RX CONSTRAINTS  —  Xilinx Vivado (.xdc)
# ---
#
# MIPI CSI-2 (Camera Serial Interface 2) is the standard interface for
# image sensors. It is a HIGH-SPEED differential serial protocol using D-PHY
# or C-PHY physical layer. Every AI vision project in 2024-2026 uses CSI-2.
#
# CSI-2 ARCHITECTURE:
#   - 1 Clock lane: differential pair carrying the byte clock (DDR)
#   - 1–4 Data lanes: differential pairs carrying serialized image data
#   - Data rate: 80 Mbps to 2.5 Gbps per lane (D-PHY v1.2)
#   - Encoding: 8-bit bytes over DDR differential pairs
#
# FPGA IMPLEMENTATION OPTIONS:
#
#   Option 1: MIPI D-PHY IP + CSI-2 RX Subsystem IP (Xilinx PG232 + PG232)
#     → Recommended. Xilinx provides a complete CSI-2 RX Subsystem IP that
#       handles D-PHY, lane merging, packet decoding, and AXI4-Stream output.
#       ALL timing constraints are generated by the IP. Do not hand-write them.
#
#   Option 2: IBUFDS_DIFF_OUT + IDELAYE2 + ISERDESE2 (manual, 7-Series)
#     → For 7-Series where MIPI IP is not available. Requires manual
#       source-synchronous constraints as documented below.
#
#   Option 3: GTH/GTY transceivers (for very high data rates > 1.5 Gbps)
#     → Uses MGT transceivers, fully constrained by the transceiver IP.
#
# THIS FILE: Covers Option 2 (manual, 7-Series) and configuration guidance
# for Option 1 (when using Xilinx IP, see comments in each section).
#
# ---


# Pin Location and I/O Standard
#
# CSI-2 uses DIFFERENTIAL pairs. On 7-Series and UltraScale+:
#   - MIPI signals connect to LVDS-capable I/O banks
#   - Use DIFF_SSTL18_I or LVDS_25 standard depending on voltage
#   - The MIPI spec requires 200-ohm differential termination at the receiver
#     (use DIFF_TERM = TRUE for on-chip termination, saves an external resistor)
#
# MIPI D-PHY electrical: 200 mV differential swing, 1.2V common mode
# Standard to use: HSUL_12 or LVDS (check your I/O bank voltage)
#
# ⚠️ BANK VOLTAGE: CSI-2 D-PHY requires the I/O bank to operate at 1.2V
# (for MIPI D-PHY compliance). Not all 7-Series banks support 1.2V.
# UltraScale+ HP banks support 1.2V and are preferred for CSI-2.

## Clock lane (differential pair)
set_property PACKAGE_PIN <CLK_P_PIN>  [get_ports mipi_clk_p]
set_property PACKAGE_PIN <CLK_N_PIN>  [get_ports mipi_clk_n]

## Data lane 0 (required — always present)
set_property PACKAGE_PIN <D0_P_PIN>   [get_ports {mipi_data_p[0]}]
set_property PACKAGE_PIN <D0_N_PIN>   [get_ports {mipi_data_n[0]}]

## Data lane 1 (for 2-lane sensors — OV5640, IMX219, etc.)
set_property PACKAGE_PIN <D1_P_PIN>   [get_ports {mipi_data_p[1]}]
set_property PACKAGE_PIN <D1_N_PIN>   [get_ports {mipi_data_n[1]}]

## Data lane 2 (for 4-lane sensors — IMX477, AR1335, etc.)
# set_property PACKAGE_PIN <D2_P_PIN>   [get_ports {mipi_data_p[2]}]
# set_property PACKAGE_PIN <D2_N_PIN>   [get_ports {mipi_data_n[2]}]

## Data lane 3
# set_property PACKAGE_PIN <D3_P_PIN>   [get_ports {mipi_data_p[3]}]
# set_property PACKAGE_PIN <D3_N_PIN>   [get_ports {mipi_data_n[3]}]

## I/O standard (use LVDS for 2.5V bank, or HSUL_12 for 1.2V bank)
set_property IOSTANDARD LVDS_25  [get_ports mipi_clk_p]
set_property IOSTANDARD LVDS_25  [get_ports mipi_clk_n]
set_property IOSTANDARD LVDS_25  [get_ports {mipi_data_p[*]}]
set_property IOSTANDARD LVDS_25  [get_ports {mipi_data_n[*]}]

## On-chip differential termination (saves external 200-ohm resistor)
set_property DIFF_TERM TRUE [get_ports mipi_clk_p]
set_property DIFF_TERM TRUE [get_ports mipi_clk_n]
set_property DIFF_TERM TRUE [get_ports {mipi_data_p[*]}]
set_property DIFF_TERM TRUE [get_ports {mipi_data_n[*]}]


# CSI-2 Clock Constraint (D-PHY HS mode)
#
# The CSI-2 clock lane carries the byte clock in High Speed (HS) mode.
# The byte clock frequency = (lane data rate / 2) because it's DDR.
#
# Common sensor data rates and byte clock periods:
#   OV5640 (2-lane, 720p@30): 420 Mbps/lane → 420/2 = 210 MHz → period = 4.762 ns
#   IMX219 (2-lane, 1080p@30): 912 Mbps/lane → 912/2 = 456 MHz → period = 2.193 ns
#   OV8865 (4-lane, 4K@15): 640 Mbps/lane → 640/2 = 320 MHz → period = 3.125 ns
#
# Check your sensor datasheet for the exact MIPI_CLK frequency.
# Formula: period_ns = 2000.0 / lane_data_rate_Mbps
#
create_clock -period 4.762 -name mipi_clk [get_ports mipi_clk_p]
#             ^^^^^ Adjust to your sensor's byte clock period


# Source-Synchronous DDR Input Delays
#
# In CSI-2 HS mode, data is transmitted DDR — one bit on each clock edge.
# After deserialization (using ISERDESE2), 8 bits are recovered per lane per
# byte clock cycle.
#
# The D-PHY timing spec (D-PHY v1.2, Section 9.1):
#   tHS-SETTLE: 85–145 ns after lane enable — handled by IDELAYE2 calibration
#   tHS-ZERO:   Data valid window = 40% of bit period minimum
#   tHSPrepare: Deassertion of LP mode before HS data
#
# For the ISERDESE2-based receiver, Vivado can use the following:
#   The IDELAYE2/IDELAYE3 delay tap number is calibrated at runtime (training).
#   Static timing constraints on ISERDESE2 outputs are NOT reliable — the delay
#   is dynamic. Instead, use ASYNC_REG attributes on the receiver output FFs
#   and rely on the lane training logic.
#
# CDC: The deserialized data from the MIPI clock domain must be transferred to
# the application clock domain via an async FIFO.
set_clock_groups -asynchronous \
    -group [get_clocks mipi_clk] \
    -group [get_clocks sys_clk]


# Camera Control Interface (I2C to sensor)
#
# Almost all image sensors are configured via I2C (called SCCB in Sony sensors).
# These are slow, async signals — apply false path.

set_property PACKAGE_PIN <CAM_SCL_PIN>  [get_ports cam_scl]
set_property PACKAGE_PIN <CAM_SDA_PIN>  [get_ports cam_sda]
set_property PACKAGE_PIN <CAM_RST_PIN>  [get_ports cam_rst_n]
set_property PACKAGE_PIN <CAM_PWDN_PIN> [get_ports cam_pwdn]

set_property IOSTANDARD LVCMOS33 [get_ports cam_scl]
set_property IOSTANDARD LVCMOS33 [get_ports cam_sda]
set_property IOSTANDARD LVCMOS33 [get_ports cam_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports cam_pwdn]

set_false_path -from [get_ports cam_scl]
set_false_path -from [get_ports cam_sda]
set_false_path -to   [get_ports cam_scl]
set_false_path -to   [get_ports cam_sda]
set_false_path -to   [get_ports cam_rst_n]
set_false_path -to   [get_ports cam_pwdn]


# ---
# #
# For any production design, use Xilinx MIPI CSI-2 RX Subsystem IP (PG232).
# It provides:
#   - Complete D-PHY RX implementation (HS + LP modes)
#   - Automatic lane training and deskew
#   - AXI4-Stream output (video pixels, packet headers)
#   - Auto-generated timing constraints
#   - Support for 1–4 data lanes
#
# Available for 7-Series (via SelectIO), UltraScale, UltraScale+, Versal.
# Free for evaluation in Vivado; production use requires a license.
#
# COMPATIBLE BOARDS FOR MIPI CSI-2:
#   - PYNQ-Z2 (camera connector)
#   - Arty Z7 (RPi camera header via adapter)
#   - ZCU104 (4-lane MIPI CSI-2)
#   - Kria KV260 (Sony IMX547 image sensor)
