# ---
# DDR3 SDRAM TIMING CONSTRAINTS  —  Xilinx Vivado (.xdc)
# ---
#
# DDR3 (Double Data Rate 3) is the most complex FPGA interface to
# constrain correctly. Data is captured on BOTH rising and falling edges of
# the clock, making it truly double-data-rate.
#
# KEY INSIGHT: In virtually all production Xilinx FPGA designs, DDR3 is
# implemented using the MIG (Memory Interface Generator) IP. MIG auto-generates
# ALL DDR3 timing constraints in a separate .xdc file (user_design/constraints/).
# YOU SHOULD USE MIG's GENERATED XDC, NOT HAND-WRITE DDR3 CONSTRAINTS.
#
# This file covers:
#   A) The constraints MIG generates (so you understand what they do)
#   B) Any additional constraints YOU need to add for the memory interface
#   C) System clock constraints for the MIG reference clock inputs
#
# When NOT using MIG (e.g., custom memory controllers, educational designs):
#   This file gives you the starting point, but hand-written DDR3 constraints
#   require detailed knowledge of your specific timing topology.
#
# ---


# System Clock for MIG Reference
#
# MIG requires two clock inputs:
#   1. A reference clock (usually 200 MHz) for the IODELAY calibration
#   2. A system clock (your application clock, e.g., 100 or 333 MHz)
#
# On Artix-7 / Kintex-7 boards:
#   - The on-board oscillator (100 or 200 MHz) feeds directly into MIG
#   - MIG's internal PLL multiplies it to the DDR3 operating frequency
#
# Define the primary clock for MIG's reference input:
create_clock -period 5.0 -name sys_clk_200 [get_ports sys_clk_p]
#   ^^^ 5.0 ns = 200 MHz reference clock (adjust if your board has a different ref)

# If your reference clock is single-ended:
# create_clock -period 5.0 -name sys_clk_200 [get_ports sys_clk]


# MIG-Generated Constraints (for reference — MIG writes these)
#
# When you use MIG, it generates a complete constraints file. The key constraints
# it creates for DDR3 are summarized here for educational purposes:
#
# 2a. Generated clocks from MIG's internal MMCM:
#
#   MIG creates MMCM outputs for:
#     - mem_clk     : DDR3 clock to DRAM chip (e.g., 333 or 400 MHz)
#     - mem_clk_ref : 200 MHz reference for IODELAYs
#     - mem_clk_200 : 200 MHz clock for IDELAYCTRL
#     - ui_clk      : User interface clock (mem_clk / 4, e.g., 83 or 100 MHz)
#
#   Example (auto-generated by MIG, DO NOT copy-paste — use MIG's actual output):
#   create_generated_clock -name mem_clk -source [get_pins mig_7series_0/.../CLKIN1] ...
#
# 2b. I/O delays for DQ, DQS, DM:
#
#   MIG generates set_input_delay and set_output_delay constraints for all
#   DQ (data), DQS (data strobe), and DM (data mask) pins.
#   These are highly specific to the DDR3 SDRAM chip's timing parameters.
#
# 2c. False paths for async reset and status:
#   set_false_path -from [get_ports sys_rst]
#   set_false_path -to   [get_ports {led[*]}]


# Additional Constraints YOU Must Add
#
# MIG's generated XDC does NOT contain constraints for your application logic.
# You need to add these:
#
# 3a. Constrain your application clock (ui_clk domain):
#     MIG names it — look in the generated XDC for the ui_clk net name.
#     Usually something like mig_inst/u_ddr3_infrastructure/gen_ui_extra_clocks.mmcm_i/CLKOUT6
#
# 3b. Clock domain crossing between sys_clk and ui_clk:
#     (See timing-patterns/clock-domain-crossing/async-cdc.xdc)
set_clock_groups -asynchronous \
    -group [get_clocks sys_clk_200] \
    -group [get_clocks -include_generated_clocks -of_objects [get_nets mig_inst/ui_clk]]


# Pin Location Template (Artix-7, Kintex-7)
#
# Replace ALL pin numbers with your actual board values.
# Your board's reference manual or MIG's pre-filled XDC is the source of truth.
#
# --- DDR3 Clock Differential Pair ---
set_property PACKAGE_PIN <DRAM_CLK_P_PIN>  [get_ports ddr3_ck_p]
set_property PACKAGE_PIN <DRAM_CLK_N_PIN>  [get_ports ddr3_ck_n]
set_property IOSTANDARD  DIFF_SSTL15       [get_ports ddr3_ck_p]
set_property IOSTANDARD  DIFF_SSTL15       [get_ports ddr3_ck_n]

# --- DDR3 Data Bus (x16 configuration example) ---
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dq[*]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_dm[*]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_p[*]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3_dqs_n[*]}]

# --- DDR3 Address and Control ---
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[*]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_ba[*]}]
set_property IOSTANDARD SSTL15 [get_ports ddr3_ras_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cas_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_we_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_reset_n]
set_property IOSTANDARD SSTL15 [get_ports ddr3_cke]
set_property IOSTANDARD SSTL15 [get_ports ddr3_odt]

# --- Drive strength for DDR3 control signals ---
set_property DRIVE 12 [get_ports {ddr3_addr[*]}]
set_property DRIVE 12 [get_ports {ddr3_ba[*]}]
set_property DRIVE 12 [get_ports ddr3_ras_n]
set_property DRIVE 12 [get_ports ddr3_cas_n]
set_property DRIVE 12 [get_ports ddr3_we_n]
set_property DRIVE 12 [get_ports ddr3_reset_n]
set_property DRIVE 12 [get_ports ddr3_cke]
set_property DRIVE 12 [get_ports ddr3_odt]


# IODELAY Configuration
#
# DDR3 requires IDELAYCTRL to be present in each I/O column used by the memory.
# This is instantiated in your RTL (or by MIG automatically).
# The 200 MHz reference clock must be connected to IDELAYCTRL's REFCLK input.
#
# In your RTL (auto-done by MIG, manual if custom controller):
#   IDELAYCTRL u_idelayctrl (
#     .REFCLK (clk_200mhz),
#     .RST    (rst),
#     .RDY    (idelay_rdy)
#   );
#
# No additional XDC needed for IDELAYCTRL itself — just ensure the 200 MHz
# clock is properly constrained (see Section 1 above).


# ---
# #
# Use MIG IP for DDR3. It:
#   1. Generates a complete, correct XDC automatically
#   2. Handles all DQ/DQS calibration automatically
#   3. Has been tested by Xilinx on the actual DRAM timing parameters
#
# Hand-writing DDR3 constraints is only necessary when:
#   - Building a custom memory controller (research/educational)
#   - Targeting an FPGA family MIG doesn't support
#   - You need specific timing overrides for layout-constrained boards
#
# VERIFICATION:
#   After implementation: report_timing_summary -datasheet
#   Check: no_input_delay, no_output_delay violations on DDR3 pins
