# ---
# DDR3 SDRAM CONSTRAINTS  —  Intel Quartus Prime (.sdc)
# ---
#
# For Intel FPGAs, DDR3 is almost always implemented using
# the Quartus External Memory Interface (EMIF) IP or UniPHY IP. These IPs
# auto-generate a complete, correct SDC file — use that, not this file.
#
# This file documents:
#   A) How to include EMIF/UniPHY auto-generated SDC
#   B) System clock constraints needed alongside the memory interface
#   C) CDC between memory controller UI clock and your application clock
#
# ---

set_time_format -unit ns -decimal_places 3


# ---
# STEP 1: Include the EMIF / UniPHY auto-generated SDC
# ---
#
# When you instantiate the EMIF IP, Quartus generates a <ip_name>_parameters.tcl
# and a timing constraints file. You must source it in your project SDC:
#
# source <your_ip_name>/<your_ip_name>_<part_number>_parameters.tcl
# source <your_ip_name>/<your_ip_name>_<part_number>_pin_map.tcl
# source <your_ip_name>/<your_ip_name>_<part_number>.sdc
#
# These are generated in the IP output directory. Add them to your .qsf:
#   set_global_assignment -name SDC_FILE <ip_name>.sdc


# ---
# STEP 2: Primary system clock
# ---
#
# The EMIF IP needs a reference clock. Define it here.
# Common: 50 MHz oscillator on DE10-Nano, DE1-SoC, etc.
create_clock -name {sys_clk} -period 20.000 -waveform {0.000 10.000} \
    [get_ports {clk}]

# DDR3 reference clock (if separate from system clock — e.g., 400 MHz for DDR3-800)
# create_clock -name {ddr3_ref_clk} -period 5.000 -waveform {0.000 2.500} \
#     [get_ports {ddr3_ref_clk}]

derive_pll_clocks
derive_clock_uncertainty


# ---
# STEP 3: CDC between DDR3 controller clock (afi_clk) and your application clock
# ---
#
# The EMIF/UniPHY controller exposes an AFI (AFI Interface) clock to your logic.
# This clock is typically sys_clk/2 or sys_clk/4 and is generated by the
# internal PLL. It's synchronous to sys_clk but at a different frequency.
#
# If your application logic runs on a different async clock, declare it:
#
# set_clock_groups -asynchronous \
#     -group [get_clocks {*afi_clk*}] \
#     -group [get_clocks {your_app_clk}]


# ---
# STEP 4: False paths for async reset and status signals
# ---
set_false_path -from [get_ports {mem_reset_n}]
set_false_path -from [get_ports {sys_rst_n}]
