# ---
# HDMI OUTPUT CONSTRAINTS (TMDS)  —  Intel Quartus Prime (.sdc)
# ---
#
# HDMI via TMDS on Intel FPGAs is typically implemented using:
#   - ALTLVDS_TX IP (serializer, generates TMDS bitstream)
#   - OR direct SERDES primitives (ALTDDIO_OUT for bit-banged TMDS)
#
# Timing approach: TMDS uses embedded clock recovery at the receiver.
# The receiver reconstructs timing from the TMDS clock channel, not from
# set_output_delay analysis. Apply false_path to TMDS output ports.
#
# Reference: HDMI 1.4 Specification, Section: TMDS Electrical
# ---

set_time_format -unit ns -decimal_places 3


# ---
# System and pixel clocks
# ---

# System clock (board oscillator)
create_clock -name {sys_clk} -period 20.000 [get_ports {clk}]

# HDMI pixel clock — generated by PLL from sys_clk
# derive_pll_clocks will automatically create this after PLL instantiation.
derive_pll_clocks
derive_clock_uncertainty

# Pixel clock domain is asynchronous to sys_clk domain
# (The PLL output is a generated clock — still isolate from other async domains)
set_clock_groups -asynchronous \
    -group [get_clocks {sys_clk}] \
    -group [get_clocks -include_generated_clocks {*pixel_clk*}]


# ---
# False paths on all TMDS output ports
# ---
#
# TMDS signals are self-timed (clock embedded in the TMDS clock channel).
# The HDMI receiver uses CDR — it does not use a reference from your FPGA.
# Quartus cannot meaningfully analyze timing to a CDR receiver.
# Apply false_path to suppress irrelevant timing reports.

set_false_path -to [get_ports {tmds_data_p[*]}]
set_false_path -to [get_ports {tmds_data_n[*]}]
set_false_path -to [get_ports {tmds_clk_p}]
set_false_path -to [get_ports {tmds_clk_n}]


# ---
# Pin I/O standard (in .qsf, not .sdc — shown here for reference)
# ---
#
# For Cyclone IV / V LVDS output:
#   set_instance_assignment -name IO_STANDARD LVDS -to tmds_data_p[*]
#   set_instance_assignment -name IO_STANDARD LVDS -to tmds_clk_p
#
# For devices without native LVDS TX (e.g., Cyclone IV GX):
#   Use ALTLVDS_TX IP with serialization factor of 10 (for TMDS 10:1)
#
# True HDMI/TMDS compliance requires 3.3V TMDS electrical levels.
# Some Intel FPGA families use LVDS (2.5V differential) which may not meet
# strict HDMI electrical compliance — verify with your board's HDMI driver
# circuit (e.g., TFP410 or direct connection with current-limiting resistors).
